### ISSUE TITLE
internet check  - google.com

### ISSUE THREAD

**Issue by csloz** [bbond007/MiSTer_ScummVM#1]
google.com is a bad choice for the is internet working test  - suggest use github.com (as you're pulling from there anyway!)

Why? - blocked in China (so the script fails).

**Comment by bbond007** [comment]
Excellent suggestion. I will make that change. Although most stuff gets pulled from http://http.us.debian.org. I assume that is OK in China?

Were you able to get the ScummVM_Installer.sh to work otherwise?

**Comment by csloz** [comment]
debian is a fine choice, no issues.

Installer worked out ok, but running the ScummVM_2_0_0.sh script sits at the starting video mode first run
Second run, it worked though - I get to the ScummVM menu.

I’m running via F12 -> scripts / ScummVM_2_0_0

Next I need to download my GOG files, and copy over to the folders. Looking forward to that!

**Comment by bbond007** [comment]
You can start it from the "Scripts" menu

**Comment by bbond007** [comment]
I have updated the ScumVM_Installer.sh to use 

"INTERNET_CHECK=https://github.com"
