### ISSUE TITLE
More/better scaling options?

### ISSUE THREAD

**Issue by Merlkir** [bbond007/MiSTer_ScummVM#10]
Hey, so I just found out the main ScummVM does not support any larger integer scaling than 3x, Which is, frankly, moronic. 
I have a 1600x1200 monitor and should be able to play pixel "perfect" (with ratio adjusted, obvs.) in 5x scale. But no, I'm forced to tell ScummVM my resolution is actually 640x480 and play with black bars on every side. 
This is dumb. 
I googled and the forums are full of people confused why this has been left hanging for years now. 
And this guy changed the source code of the 3x scaler to 6x:
https://forums.scummvm.org/viewtopic.php?t=14060
I'm not asking for any actual filters, like TV or DOTmatrix, although those would be lovely to have.
Just normal scaling, which should not be difficult. (?)
Could this be added?

**Comment by bbond007** [comment]
You are not forced to do anything dumb...
