### ISSUE TITLE
scummmodern isnt showing up

### ISSUE THREAD

**Issue by graschbaten** [bbond007/MiSTer_ScummVM#11]
Hi, how is it possible to change the theme? 
I setup the theme folder with scummmodern.zip in it and apply these changes. 
after this scummmodern isnt showing up in misc/themes

**Comment by bbond007** [comment]
The format of these theme files sometimes change and become incompatible.

you probably want scummmodern22.zip. Just  rename to scummmodern.zip

**Comment by graschbaten** [comment]
Thx, few minutes ago i see you have the correct themes to download. 

This works for me!
