### ISSUE TITLE
SDL failed to find video mode for 640x400

### ISSUE THREAD

**Issue by Televicious** [bbond007/MiSTer_ScummVM#12]
Tried running out of vga port and direct video on hdmi and get this message. Trying to run on a Commodore 1084. Does this only run in HDMI scaled video mode?

**Comment by bbond007** [comment]
Copy ScummVM_2_2_0.sh to ScummVM_2_2_0_320x200.sh

Edit  ScummVM_2_2_0_320x200.sh

```
echo "Setting Video mode..."
vmode -r 320 200 rgb16
```

You can run in 320x200 mode if you must first boot into 640x480 mode and make changes:

Graphics Mode : Normal (no scaling)
Render Mode : <default>

[ ] aspect ratio correction
[ ] Fullscreen Mode
[ ] Filter Graphics

(basically unchecked all)

Be aware you will be limiting the library of games you can run quite extensively as many newer need 640x480...

**Comment by Saroumane** [comment]
Hello @Televicious did you manage to run ScummVM in 320x200 ?

@bbond007 
I did everything you said above (on ScummVM_2_8_1.sh) and I even boot in 640x480, but when I try in 320x200 I still have :
WARNING : SDL_SetVideoMode says we can't switch to that mode (No video mode large enough for 640x400) !
Any advice ? Thanks !

**Comment by Televicious** [comment]
Yea! It was pretty awesome to see vga at 240p.
I put pics on mister FB page like 4 years ago.

**Comment by Televicious** [comment]
Sorry man, I actually uninstalled that ages ago and have it all hooked up
to a 4k display now.  Per my old forum post "Disable scaling in the
graphics menu, modify the .sh file so it's -r 320 240 rgb16. I think -r 320
200 rgb16 will work too. Will run anything prior to curse of monkey island
or broken sword."
Here's a screen pic of qg4 on my 1084 though.

Best of luck,


Jason

**Comment by Saroumane** [comment]
Yeah, it works !

And if there is no other display available, it's also easy to edit
` /sdcard/ScummVM/.config/scummvm/scummvm.ini`

and put these values: 
```
[scummvm]
scale_factor=1
scaler=normal
```

Now I have to find the right settings to have sound
