### ISSUE TITLE
shared library not found: libdb-5.3.so

### ISSUE THREAD

**Issue by kng** [bbond007/MiSTer_ScummVM#14]
Fresh install of MiSTer, updated.
Running the installer with default settings, installer finishes OK.
When running ScummVM_2_2_0.sh i get the error:
scummvm22: error while loading shared libraries: libdb-5.3.so (file not found)

**Comment by estevan1973** [comment]
Same for issue happend for me. After update of MISTer an error message appears:
error while loading shared libraries: libdb-5.3.so
cannot open file or directory

**Comment by kng** [comment]
Aha, so it was part of a older mister linux.img
I pulled a 2 year old image [image](https://github.com/MiSTer-devel/SD-Installer-Win64_MiSTer/blob/master/release_20200122.rar) found it in /usr/lib/libdb-5.3.so
It can be put in with the other libs in ScummVM/arm-linux-gnueabihf

Temporary [uploaded it to my drive](https://drive.google.com/file/d/10aUAmPgxYJVLhogBNxrSVic0wtZxhtzz/view?usp=sharing) if someone want to test it without extracting it from the image. mount -o loop etc.

**Comment by kng** [comment]
I have tried the [debian bullseye](https://packages.debian.org/bullseye/libdb5.3) deb and it also seems to work. This can probably be put in the DEBS directory of this repo as a solution for this problem.

**Comment by bbond007** [comment]
Fixed
