### ISSUE TITLE
Template Install_ScummVM.ini

### ISSUE THREAD

**Issue by RolandKaechele** [bbond007/MiSTer_ScummVM#16]
Can you please add a template file for Install_ScummVM.ini (e.g. Install_ScummVM.ini.template) which can be copied and then adapted?

BR
Roland

**Comment by bbond007** [comment]
Its not wrong, you are supposed to run Install_ScummVM.sh which downloads a fresh ScummVM_Installer.sh. 

This design is based on Locutus73's "Updater script for MiSTer".  Install_ScummVM.sh only needs to be downloaded once initially and not when updating or reinstalling.

[README.md --> ](https://github.com/bbond007/MiSTer_ScummVM/blob/master/README.md)

```
Install instructions: 

    Run Install_ScummVM.sh
    Install options can be set in Install_ScummVM.ini 
```

**Comment by RolandKaechele** [comment]
I have nothing said about the sh file. I have talked about the naming of the ini file.

**Comment by flynnsbit** [comment]
> I have nothing said about the sh file. I have talked about the naming of the ini file.

You are using the wrong installer.sh file if your .ini file wants ScummVM_Installer.ini.  Make sure you download ScummVM_Installer.sh and then you can use Install_ScummVM.ini file as referenced in the readme.

**Comment by RolandKaechele** [comment]
Okay. Is it possible to add a ini template file which can be copied and then adapted for easier installer usage?

**Comment by bbond007** [comment]
Install_ScummVM.ini.template added
