### ISSUE TITLE
mt32pi sound request

### ISSUE THREAD

**Issue by riper** [bbond007/MiSTer_ScummVM#17]
First of all **thanks** for bringing ScummVM to Mister.
I join the request to add mt32pi support to ScummVM.
Scummvm is a very easy to use tool with hundreds of _plug'n'play_ games ready to be played. Without problems of configuration of graphics, sound, mouse, etc ...
I repeat: thank you very much for making the port, but we would appreciate it if you could make the adaptation.
Sincerely.

**Comment by bbond007** [comment]
![ScummVM-mt32pi](https://user-images.githubusercontent.com/2729009/158711676-6ac50b28-d718-4b97-8a49-2d7584ff9a9c.jpg)

getting close...

**Comment by riper** [comment]
Amazing!! I'm sure you'll make a lot of people **happy** (me first)

**Comment by bbond007** [comment]
let me know how it works for you...
thanks!

[MIDIMeister.zip](https://github.com/bbond007/MiSTer_ScummVM/files/8319687/MIDIMeister.zip)

**Comment by bbond007** [comment]
If this works I'll make it an install option :)

**Comment by riper** [comment]
OKAY. I'm at work right now. When I get home I will test it and report back. Thank you very much!

**Comment by riper** [comment]
I have to say that my mt32pi device is that one: [Link](https://www.antoniovillena.es/store/product/mt32pi-yavimaya/)
It is a device that on the one hand connects to the Mister using USER_IO through the DB9 port and on the other connects to a raspyberry pi using it's GPIO (with the roms, soundfonts, ...)

Something like this:

[Mister DB9]<---------DB9 extend cable ----------->[mt32pi+raspberry]

(Not at home yet)

**Comment by BobRedthorp** [comment]
> 

I get  LSL3, SQ3, Codename Iceman working fine (just some stuttering), it seems to be the larger Sierra games like lsl6 and freddy pharkas, I know some games can look like they've crashed as the send the data but it seems too long

**Comment by Schermobianco** [comment]
from my tests it seems to only work on sierra games

**Comment by riper** [comment]
I have to say that I have had no luck with the tests.

My mt32pi device connects to the Mister via the DB9 port... and I guess @Schermobianco and @BobRedthorp connect via USB.

I have started with a fresh installation of ScummVM.
- Put the ScummVM_Installer.sh inside /media/fat/Scripts
- Run the script
- Download the files
This downloads version 2.3 of ScummVM

And then I proceed to execute the commands you left in the README.TXT of the MIDIMeister.zip:
- Copy menu.rbf to /media/fat
- Copy MIDIMeister to /media/fat/linux
- Copy ScummVM_2_5_1.sh to /media/fat/Scripts

When I run the script ScummVM_2.5.1 from /media/fat/Scripts it successfully runs ScummVM 2.5.1
I go to "MIDI" menu and select "MIDIMeister (mt32pi) [ALSA]" and apply the changes.

When I'm about to test a game (for example MI and MI2) the game sounds the same whether I have the mt32pi connected to the Mister or not. I'd say it's "SoundBlaster" sound I hear.

I don't know if I am doing something wrong or my mt32pi is invalid for this.

**Comment by Schermobianco** [comment]
> I have to say that I have had no luck with the tests.
> 
> My mt32pi device connects to the Mister via the DB9 port... and I guess @Schermobianco and @BobRedthorp connect via USB.
> 
> I have started with a fresh installation of ScummVM.
> - Put the ScummVM_Installer.sh inside /media/fat/Scripts
> - Run the script
> - Download the files
> This downloads version 2.3 of ScummVM
> 
> And then I proceed to execute the commands you left in the README.TXT of the MIDIMeister.zip:
> - Copy menu.rbf to /media/fat
> - Copy MIDIMeister to /media/fat/linux
> - Copy ScummVM_2_5_1.sh to /media/fat/Scripts
> 
> When I run the script ScummVM_2.5.1 from /media/fat/Scripts it successfully runs ScummVM 2.5.1
> I go to "MIDI" menu and select "MIDIMeister (mt32pi) [ALSA]" and apply the changes.
> 
> When I'm about to test a game (for example MI and MI2) the game sounds the same whether I have the mt32pi connected to the Mister or not. I'd say it's "SoundBlaster" sound I hear.
> 
> I don't know if I am doing something wrong or my mt32pi is invalid for this.

Try this:
On global option set Audio, Midi and MT-32 to MIDIMeister, apply all modification then exit to mister menu and restart scummvm251

**Comment by Schermobianco** [comment]
@riper yes I'm with USB

**Comment by bbond007** [comment]
Think I have eliminated hiccups/tempo issues

[MIDIMeister.zip](https://github.com/bbond007/MiSTer_ScummVM/files/8337537/MIDIMeister.zip)

Good luck and thanks for testing!

**Comment by bbond007** [comment]
> @riper yes I'm with USB

USB does not need this driver at all...

**Comment by Schermobianco** [comment]
> > @riper yes I'm with USB
> 
> USB MIDI does not need this driver at all...  
> 
> Unless its a USB serial device, and that case I'll have to modify the driver to let the user specify the serial port. It assumes /dev/ttyS1...
> 

I mean I/O port with USB connector

**Comment by riper** [comment]
@Schermobianco I've tested your configuration (set Audio, Midi and MT-32 to MIDIMeister, apply all modification then exit to mister menu and restart scummvm251) and it doesn't work. On MI2, for example, there is no sound, just the voices of Guybrush and Eleine.

@bbond007 , I think my mt32pi uses a DB9 port instead of a USB port, but both use the USER_IO.
Is there a way to adapt your midi version of ScummVM to DB9?

Thanks.

**Comment by Schermobianco** [comment]
@riper same log on startup here and the driver is working

**Comment by riper** [comment]
**Finally I have sound !!**

What I did:
- Remove any old installation of ScummVM from my Mister
- Take the [Install_ScummVM.sh](https://github.com/bbond007/MiSTer_ScummVM/blob/master/Install_ScummVM.sh) and put it on /media/fat/Scripts
- Take the [Install_ScummVM.ini.template](https://github.com/bbond007/MiSTer_ScummVM/blob/master/Install_ScummVM.ini.template) and put it on /media/fat/Scripts
- Rename it to "Install_ScummVM.ini" ( mv Install_ScummVM.ini.template Install_ScummVM.ini )
- Run from cmd the install script ( ./Install_ScummVM.sh )
- The process will install ScummVM versions: 2.3, 2.5, 2.5.0 and 2.5.1
- Download the lastest MIDIMiester.zip from that thread and unzip it
- Follow the instructions from the README.TXT

The script that worked for me is "ScummVM_2_5_1.sh" from the .zip
I haven't found any bugs yet. Well, the truth is that I haven't tried many games... I've come running to the PC to report!

Again: thank you for doing that, @bbond007 !!!

I will follow this thread attentive to the news.   :-)

**Comment by bbond007** [comment]
>  I have some lib errors on the screen (before ScummVM gui appears)
> 

Those are just warnings (not errors) caused by the libasound.so.2 included with MiSTer not being compiled with version information. They are benign and don't seem to cause any issues. 

Eventually I'll get around to fixing them, but for now just ignore them...

**Comment by BobRedthorp** [comment]
> Think I have eliminated hiccups/tempo issues...
> 
> [MIDIMeister.zip](https://github.com/bbond007/MiSTer_ScummVM/files/8341464/MIDIMeister.zip)
> 
> Good luck and thanks for testing!

Great stuff! no more tempo or sound hiccups at my end!

Edit: I also should add I don't have the black screen on the other titles I mentioned (whatever the cause of that was)

**Comment by Schermobianco** [comment]
@bbond007 this driver is awesome!! Thanks Man!

**Comment by wizzomafizzo** [comment]
Just chiming in this is working great for me too. No audio issues so far as much as I can tell

**Comment by bbond007** [comment]
MIDIMeister is now installed automatically. Closed :)
