### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by TuKo1982** [bbond007/MiSTer_ScummVM#24]
Just built a new MiSTer setup from scratch and ran your script to install ScummVM 2.5 and 2.5.1. Running ScummVM I get a lot of errors regarding libraries unable to check for versions. As a result, I have no audio when playing games.

**Comment by bbond007** [comment]
the version stuff is warnings, not errors. Ignore it. 

Your sound issue is most likely something else.

**Comment by TuKo1982** [comment]
Indeed. Reinstalled from scratch and now it works.
