### ISSUE TITLE
Typos in ScummVM_Installer.sh

### ISSUE THREAD

**Issue by ojaksch** [bbond007/MiSTer_ScummVM#26]
Thanks for the new update, which "failed" to install 2.6.1 to my MiSTer.
I was wondering why I'm still at 2.5.1 after the install of 2.6.1 and had a look at ScummVM_Installer.sh, where I found some typos beginning from line 304. Looks like not-aligned copy'n paste errors ;)
Maybe there are more typos, but these caught my eye:

ie: line 304
```
	if [ "$BBOND007_SCUMMVM251_UNSTABLE" = "TRUE" ];
	then
		echo "Downloading --> BBond007_ScummVM_2_5_0_Unstable..."
```

line 354 (this is why one can't update to 2.6.1)
```
	if [ "$BBOND007_SCUMMVM251" = "TRUE" ];
	then
		echo "Downloading --> BBond007_ScummVM_2_6_1..."
```

line 364
```
	if [ "$BBOND007_SCUMMVM261_UNSTABLE" = "TRUE" ];
	then
		echo "Downloading --> BBond007_ScummVM_2_6_0_Unstable..."
```

**Comment by bbond007** [comment]
Ok, sorry about that... fixed

**Comment by ojaksch** [comment]
Great! Let the games begin :)
