### ISSUE TITLE
New compilation of scummvm251

### ISSUE THREAD

**Issue by Kamil303** [bbond007/MiSTer_ScummVM#28]
Hi.
The Longest Journey and Zork Nemesis are running on scummvm251, which was compiled in March.
They don't work on scummvm251 that was compiled now.

**Comment by bbond007** [comment]
I think I may have disabled ResidualVM engine engine as the performance on the MiSTer HPS is not great...

I'll check and follow up...

**Comment by bbond007** [comment]
I went back to my original 2.51 and Nemesis crashes.... You sure it worked?

**Comment by Kamil303** [comment]
Yes, both Zork Nemesis and TLJ work in old scummvm251. They don't work in new scummvm251 and also in scummvm261: engine not found.
I am attaching my scummvm.ini file, ver. 251
[scummvm.zip](https://github.com/bbond007/MiSTer_ScummVM/files/10066120/scummvm.zip)

**Comment by bbond007** [comment]
2.5.X - 2.6.X have been updated to include ResidualVM engine - even though Longest Journey preforms too poorly to be enjoyable in my opinion...
