### ISSUE TITLE
Please enable the ScummVM shader system

### ISSUE THREAD

**Issue by parkamonster** [bbond007/MiSTer_ScummVM#33]
Obviously ScummVM is not a MiSTer core, so it's unable to access MiSTer's excellent video processing effects. So with that in mind, is it possible to support ScummVM's built in shader system instead?

Yes, I know there's the old built in "TV Scaler 2x" but it looks like _garbage_ compared to the new shader system.

I really love the "crt/crt-easymode.glslp" shader (included in their shader set) as it's fairly lightweight in terms of resources, while looking very authentic. I tried to add it myself with no success.

I followed the guide here, https://docs.scummvm.org/en/latest/settings/graphics.html, created an "ICONS" folder, copied shaders-20230108.dat into it, added the path, but the shader button is still greyed out, as is the button to download shaders.

Correct me if I'm wrong but it appears that you intentionally disabled this feature?

**Comment by bbond007** [comment]
The new stuff requires SDL 2.0 which requires OpenGL or ES 

That is simply not going to work on the framebuffer...

Enabling "MiSTer's excellent video processing effects" for the menu.rbf core is more realistic.

Sorry...
