### ISSUE TITLE
missing engines in newer versions ?

### ISSUE THREAD

**Issue by Saroumane** [bbond007/MiSTer_ScummVM#34]
ScummVM 2.7.1 is the last version that has AGS engine (tested with Maniac Mansion Deluxe)
Newer versions fail with "Could not find any engine capable of running the selected game" (tested with 2.8.x, Master)

**Comment by bbond007** [comment]
Thank you very much finding that regression..

I switched machines which I compile on and was missing a dependency which caused AGS engine to be unavailable.

Somehow I missed that.

Anyway, I've updated 2.8.x & Master, engine should be available now.
