### ISSUE TITLE
Version history

### ISSUE THREAD

**Issue by csloz** [bbond007/MiSTer_ScummVM#4]
Suggest add a version history in the top of the update script so that you can log the changes.

eg

```
# v1.3 - June 17 2019 - Added ScummVM 2.1 option
...
```

**Comment by rsn8887** [comment]
Also it should be communicated which actual ScummVM is bundled. For example the ScummVM 2.2 is a beta, dev build from July 2020, not 2.2.0 release, which was tagged in September 2020.

**Comment by bbond007** [comment]
2.2 has been refreshed
2.3 has been added
2.5 has been added
