### ISSUE TITLE
ScummVM from usb0

### ISSUE THREAD

**Issue by amerika13** [bbond007/MiSTer_ScummVM#5]
I have ran into an issue when trying to setup ScummVM to run from usb0 on MiSTer.

My Install_ScummVM.ini file is:
INSTALL_DIR="/media/usb0/games/ScummVM"
SCRIPTS_DIR="/media/fat/Scripts"
DEB_SCUMMVM17="FALSE"
BBOND007_SCUMMVM20="FALSE"
BBOND007_SCUMMVM21="FALSE"
BBOND007_SCUMMVM21_UNSTABLE="FALSE"
BBOND007_SCUMMVM22="TRUE"
BBOND007_SCUMMVM22_UNSTABLE="FALSE"
ENGINE_DATA="TRUE"
CREATE_DIRS="TRUE"
DEFAULT_THEME="FALSE"
INTERNET_CHECK="https://github.com"
VERBOSE_MODE="FALSE"

However, the created ScummVM_2_2_0.sh file has the HOME_DIR set to the SD card.  I tried setting this to /media/usb0/games/ScummVM but I get "permission denied" when I try to run it.

SCUMMVM_CPU_MASK=03
SCUMMVM_EXE_NAME="scummvm22"
SCUMMVM_HOME_DIR="/media/fat/ScummVM"
SCUMMVM_OPTIONS="--opl-driver=db --output-rate=48000"
SCUMMVM_LIB_PATH="$SCUMMVM_HOME_DIR/arm-linux-gnueabihf:$SCUMMVM_HOME_DIR/arm-linux-gnueabihf/pulseaudio"

**Comment by NML32** [comment]
@amerika13 See if this helps

***Set USB device execute***
in file: /etc/usbmount/usbmount.conf
edit the string: MOUNTOPTIONS="sync,noexec,nodev,noatime,nodiratime"
remove noexec
