### ISSUE TITLE
Can this be based on daily snapshots?

### ISSUE THREAD

**Issue by rsn8887** [bbond007/MiSTer_ScummVM#6]
Thanks I just found this, but I am pretty confused. Why is there no 2.1.1 stable?

Also you make it sound like 2.2.0 existed but that hasn’t been tagged yet. So your 2.2.0 is actually based on some daily git snapshot from the master branch from Oct 2019.

Improvements are made daily to the code since it is not an official release version yet. For example, the ultima engine and keymapper were recently added in the last two weeks or so.

Maybe you can update your “2.2.0“ build to something more recent than 2019 and maybe rename to git-master or so, to differentiate it from the actual 2.2.0 which will eventually be tagged officially.

**Comment by bbond007** [comment]
Sorry for the confusion...

I am in the process of testing a new build.

I really do make an effort to test thoroughly before pushing the bins to Github...

Daily snapshots builds are completely out of the question, however, I would be willing to do more frequent builds, based on milestones of the ScummVM project.

**Comment by rsn8887** [comment]
Thanks!

**Comment by rsn8887** [comment]
2.2.0 was tagged and released in September 2020. You build is from July 2020 so it is not ScummVM 2.2 rather it is 2.1 with some additions.
