### ISSUE TITLE
Scummremastered theme is not installed

### ISSUE THREAD

**Issue by rsn8887** [bbond007/MiSTer_ScummVM#7]
After installing 2.2.0 unstable, on launch, I get a WARNING: Could not find theme `scummremastered` falling back to builtin!

Can you ensure that scummremastered is installed together with scummvm? It is the default theme on all platforms now.

After I changed the Install_Default_Theme option to "TRUE" I got scummmodern, but that's not the latest either, scummremastered is.

**Comment by DwaineGarden** [comment]
+1  I get the same error

**Comment by rsn8887** [comment]
I fixed it manually by downloading "scummremastered22.zip" from here, renaming to "scummremastered.zip" and copying to my Mister into ScummVM folder.
