### ISSUE TITLE
Can this be built and bundled with SDL2 to support stretch modes?

### ISSUE THREAD

**Issue by rsn8887** [bbond007/MiSTer_ScummVM#8]
Is there an option to make ScummVM or MiSTer scale to full height at 1080p resolution?

It seems the script sets the video mode to 640x480 rgb16, but can't ScummVM display full height at 1080p rgb24, or can MiSTer scale it up? I tried to remove the command that sets the video mode to 640x480, but the ScummmVM game screen is still small, and the fullscreen option checkbox does nothing.

The recommended Mister.ini settings 
```
[MENU]
vga_scaler=1
vga_mode=6
```
make ScummVM fullscreen but the resolution is switched to 640x480 for the main menu as well as ScummVM, not just for ScummVM. In addition it is not running in 1080p, just 480p.

Hmm on Windows and MacOS, ScummVM has a stretch mode option directly underneath render mode which does what I want: it stretches the ScummVM screen to full height. But on MiSTer that setting is missing. It seems it is fixed to "center" which is 1:1 rendering in the center of the screen.

**Comment by rsn8887** [comment]
It seems this ScummVM is built with SDL1.2 not SDL2, that's why it is missing the stretch mode options.

**Comment by bbond007** [comment]
I think SDL2 features like that (not implemented in hardware) would be too much of a performance loss.
