### ISSUE TITLE
FPGA MIDI?

### ISSUE THREAD

**Issue by sigboe** [bbond007/MiSTer_ScummVM#9]
Excuse me for talking about things I know very little about (that's why i'm asking)

Would it be possible to have this program send MIDI cores to the FPGA, and have them connected to the ScummVM program?

I just think this would have the following benefits 
* Increase audio accuracy even over running on a desktop computer
* Cement this as a "legitimate" core in MiSTer
* Would be extremely cool :sunglasses: 

I think there are some MIDI FPGA running on MiSTer already, and I assume that they can be used, and the main work that needs to be done would be the connection to and from the Linux side, and maybe a bit of FPGA development as well. But that is just speculation on my part.

**Comment by bbond007** [comment]
I have never seen any serious open-source MIDI HDL projects for even General Midi. 

Really the only worthwhile one would be Roland MT-32/CM-32L and it just does not exist.

**Comment by BobRedthorp** [comment]
Would it be possible to add support for dwhinham's amazing mt32-pi? 

https://github.com/dwhinham

**Comment by RockyBoulder** [comment]
Indeed support for mt32-pi would really be great. Together with PI-Midi from aranet this would be really great to have.

**Comment by masch0** [comment]
Yes also from my side. Direct support for mt32-pi would be great. 
My Mister and additional hardware (keyboard mouse/bt/wifi dongles and the mt32-pi) are installed together in a small pult case (like retro computers). But only for scummvm currently i use an external usb/midi, 2nd mt32 device outside and audio mixer (for midi and mister audio), the internal mt32-pi cant be used (not so nice).

**Comment by bbond007** [comment]
I don't know how to access the user port (on the FPGA side) from the Linux environment. I think it would need modifications "menu" core. 

I have written an ALSA MIDI driver before, so I am certainly capable of writing the driver, but accessing the mt32-pie from linux user space is something perhaps I'd need help with.

Leaving this open for discussion, but I make no promises :)

**Comment by bbond007** [comment]
This should allow you test mt32-pi

I have not been able to test it myself (yet) because my USER-IO port on my IO board is not compatible. 

[MIDIMeister.zip](https://github.com/bbond007/MiSTer_ScummVM/files/8319708/MIDIMeister.zip)

I'm going to close this issue, but I ask that you leave any comments here --> https://github.com/bbond007/MiSTer_ScummVM/issues/17
